name: Java CI with Maven - Test and package
on: 
  pull_request: 
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: configurate java JDK 21 env 
        uses: actions/setup-java@v5
        with: 
          java-version: '21'
          distribution: 'corretto'

      - name: compile and package
        run: mvn -B package